import type { Metadata } from "next";
import { Lobster_Two, Montserrat } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/Header";

const sofia = Lobster_Two({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--cursive",
});
const prime = Montserrat({
  subsets: ["latin"],
  variable: "--cursive",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css"
        />
      </head>
      <body className={cn(prime.className, sofia.variable)}>
        <Header />
        <div className="max-w-5xl mx-auto">{children}</div>
      </body>
    </html>
  );
}
